# Generated by Django 6.0.2 on 2026-02-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wood_app', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotations',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='services',
            field=models.CharField(db_column='service', max_length=100),
        ),
    ]
